[0m22:05:01.665632 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A576A48940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A5791A8D00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A5791A8A90>]}


============================== 22:05:01.670823 | 18ef0428-3ac1-47df-a9fc-b71bb119b2f7 ==============================
[0m22:05:01.670823 [info ] [MainThread]: Running with dbt=1.7.11
[0m22:05:01.672826 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Admin\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:05:06.850406 [debug] [MainThread]: Starter project path: C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\include\starter_project
[0m22:05:06.889629 [info ] [MainThread]: 
Your new dbt project "dbt_test" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:05:06.889629 [info ] [MainThread]: Setting up your profile.
[0m22:05:06.889629 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m22:05:06.898492 [debug] [MainThread]: Command `dbt init` failed at 22:05:06.898492 after 5.27 seconds
[0m22:05:06.898492 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A576A48940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A5791A9AB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A5791A9BD0>]}
[0m22:05:06.898492 [debug] [MainThread]: Flushing usage events
